### ISSUE TITLE
Template bug

### ISSUE THREAD

**Issue by denysdesign** [datlechin/flarum-chatgpt#1]
Assistent label broken template!

Plse fix this bug

For example: https://joomla-ua.org/community/d/3108-yakii-distributiv-linux-vi-obirayete-dlya-joomla

![screenshot-joomla-ua org-2023 04 01-04_51_06](https://user-images.githubusercontent.com/1041797/229260143-a91b2eb5-08b7-4c31-aa6a-900101ed4eb2.png)

Thank you!

**Comment by datlechin** [comment]
Fixed
